### ISSUE TITLE
Anyway To Pull In The Upcoming Calendar Schedule?

### ISSUE THREAD

**Issue by dxfan227** [Kiina/MMM-trakt#12]
Hi Love The Module.

I'm not really sure where it;'s getting it's info from, the shows it's listing are shows I watch, but not really anything that makes sense to me......is there a way to pull in the info from upcomming shows calander , this shows the episodes airing today of shows I watch. Any help would be AWESOME!

**Comment by Menturan** [comment]
Hi @dxfan227 !
The module gets its data from your Trakt calendar which shows today's episodes and upcoming.
The `days` config parameter is by default set to 1 which only shows today's episodes. If you set it to 2 it will show today's and tomorrow episodes.

**Comment by dxfan227** [comment]
Strange... which calander  though for example when I go to my trakt app I see a different list of shows for airing today than I do in my progress area.

**Comment by Menturan** [comment]
Hmm strange. If you go to your https://trakt.tv/dashboard, it's what is lists under "Upcoming schedule" that's shown in the module. Maybe you are looking at "Up next to watch"? You don't have a second account so there has been a mix?

**Comment by dxfan227** [comment]
@Menturan interesting I'm not really sure that mine is pulling from there. 

Regardless, do you know how to edit the shows the show up in that area? there seem to be some in mine that I don't watch....or maybe watched one episode of once. I appreciate your help.

Also are there any good css styling options you have found to make the module a little more "pretty" any tips would be great. thanks for everyone's hard work on this.

**Comment by Menturan** [comment]
@dxfan227 Sorry, I’m pretty new to Trakt so am not really sure. I’m manually marking episodes as watch in a synced mobile app.

The styling is inspired by MagicMirrors default modules. You can add your own css in MagicMirrors root folder `/css/custom.css`. Module specific css classes is listed in `MMM-trakt/MMM-trakt.css`.

**Comment by dxfan227** [comment]
@Menturan 

no problem, my media player automatically marks things as watched for me as I watched them.....but I can't figure out a way to add shows that have not aired yet to the upcoming schedule...I only have three options add to watch list, collect, watched ....watch list doesn't do it....collected and watched can be chosen since there are no aired episodes yet. :(

**Comment by Menturan** [comment]
@dxfan227 I think [Trakt support](https://support.trakt.tv/) can better answer your questions. :slightly_smiling_face: 
The module works as expected so I'm closing this issue now.
