### ISSUE TITLE
Pulling artwork 

### ISSUE THREAD

**Issue by dxfan227** [Kiina/MMM-trakt#13]
Hi again! Don’t know if this is the right place to ask, but I’m trying to learn JavaScript.... and wanted to maybe try and edit this module to include the show artwork next to each show.

Could you maybe get me on the right track?

**Comment by Kiina** [comment]
https://github.com/vankasteelj/trakt.tv-images#readme

The trakt.tv-images node library which is included in the project can do this. I had a semi working version with it, but it's kinda hard to make it look good, show a decent amount of shows and have images in it, but if you want to try feel free. Getting the images for a show is surprisingly easy as you can see in the readme
