### ISSUE TITLE
Module dont show up

### ISSUE THREAD

**Issue by TheVieiraAkA** [Kiina/MMM-trakt#2]
Hello Kiina, i installed your module MMM-Trakt and i cant manage to use it, he just dont show up on screen, i already created the trakt application to get the API_keys, but i cant use, no error on console, jus nothing, can you help me resolving this problem or get me a sample of code with the module working? i really dont know what i am doing wrong.

**Comment by Kiina** [comment]
Oh sorry my fault, didn't test the pull request because I was on vacation and just looked over it. I pushed a new version that should fix the problem. Can you please update and report if it works now?

**Comment by TheVieiraAkA** [comment]
ya that fixed the problem, but i have another one and a question.

is it normal that every time that I restart the MagicMirror app the trak ask me for the activation code? thats anoying xD

and is there any way to filter the show episodes to show only the "unwatched" ones ?

**Comment by Kiina** [comment]
Nope that's not normal. Changed the Name but didn't change the token path. Pull the latest Version and try again, it should save the token after the first try (if not maybe it doesn't have the permissions to create the file).

Filtering unwatched is currently not possible because trakt doesn't provide that data with the "show calendar". But I will keep it in mind and look into it if it's possible to add as a feature in the future.

**Comment by TheVieiraAkA** [comment]
ya that fixed the problem.

can you teach me the code? im studiyng for software developer and i already have some knowledge in  javascript/node, mb i can try to implement the "unwatched episodes"pull configuration :D

**Comment by Kiina** [comment]
Well to be honest the code is not that complicated. [Basically the node_helper pulls all the shows](https://github.com/Kiina/MMM-trakt/blob/master/node_helper.js#L53). After that you could probably use the "shows" callback and try to filter them before returning them to the socket. [trakt.shows.watched() should probably work.](https://github.com/vankasteelj/trakt.tv/blob/HEAD/docs/available_methods.md)

**Comment by TheVieiraAkA** [comment]
thanks alot! i was already playing with the code, and i just figured that the trakt.shows.progress give me the "aired / completed" values from a Show, i think that i just need a FOR loop for all the "my show" and get the values
i'll update you when i got more info about this, thats and good work on the module!
