### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by aunrea** [Kiina/MMM-trakt#23]
The module doesn't load. No code, no errors. Even the logs have no errors listed. It's like it doesn't exist, but it is in my config and I see MMM-trakt.js in the list of loaded files. It just isn't showing anything and I have no idea why.

**Comment by Kiina** [comment]
Hm, this is really weird. I've updated my MM installation in case something broke in the meantime but it's still working for me. Mind setting the debug to true and sharing your `config.js` (with `client_id ` and  `client_secret` censored ofc) and a full boot log?

**Comment by aunrea** [comment]
Boot log: [https://pastebin.com/bZXewvSK](https://pastebin.com/bZXewvSK)

config:
```
{
			module: 'MMM-trakt',
			position: 'bottom_center', // you may choose any location
			header: 'Airing This Week', // optional
			config: {
				client_id: '********************',
				client_secret: '********************',
				days: 7, // optional, default: 1. 1 = today's episodes, 2 = today's and tomorrow's, 3 = etc...
				styling : {
					moduleSize: "small", // optional, possible value: (xsmall, small, medium, large, xlarge), default: small
					daysUntil: true, // optional, shows 'today' and 'tomorrow' insted of date, default: false
					daysUntilFormat: "hh:mm", // optional, default: "hh:mm", time format after 'today'. Leave empty ("") to hide, possible values: https://momentjs.com/docs/#/displaying/format/
					dateFormat: "D.M hh:mm", // optional, default: "D.M hh:mm", possible values: https://momentjs.com/docs/#/displaying/format/
					showEpisodeTitle: true, // optional, default: true
				},
				debug: true // optional, default: false
			}
		},
```

**Comment by aunrea** [comment]
I just looked at the web console in Chrome and saw this error message:

`Load script: modules/MMM-trakt/MMM-trakt.js
:8080/modules/MMM-trakt/MMM-trakt.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
loader.js:194 Error on loading script: modules/MMM-trakt/MMM-trakt.js
script.onerror @ loader.js:194
`

**Comment by Kiina** [comment]
Hm that is interesting. But the file MMM-trakt.js exists? Not that some download issue caused the file to be missing

**Comment by aunrea** [comment]
I reinstalled. It shows now but it says:

Error loading module.
Please check the logs.

There are no errors listed in the mm error logs.

**Comment by aunrea** [comment]
Now it is working. I had to reboot and then I finally saw the activation info. I activated it and now it works fine. So I guess it was just a bad install to start with that caused all the trouble.
