### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by kominoshja** [Kiina/MMM-trakt#6]
Hi! 
Thanks a lot for developing this module! I wanted to know if you plan to keep working on it?
Thanks!
Kominoshja

**Comment by Kiina** [comment]
Well I have no plans to abandon it, electron versions have just given me some problems in the past and after they seem sorted out, I just hadn't had the time. But as I have some more plans for the magicmirror in 2019 I will definitely update dependencies and look into a few of the todos as soon as I get physical access to my mirror back. Got anything specific in mind?

**Comment by kominoshja** [comment]
The table is a bit too big which makes it impossible to keep on all the time with other modules

**Comment by Kiina** [comment]
Oh yeah, I guess it's kinda big on lower resolution screens. Will fix this in an upcoming update

**Comment by ezar** [comment]
Please! Update with this :)
