### ISSUE TITLE
Module doesnt works :(

### ISSUE THREAD

**Issue by ezar** [Kiina/MMM-trakt#7]
I cannot use it :(

0|MagicMir | (node:3465) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: OAuth required
0|MagicMir | (node:3465) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Kiina** [comment]
Have you tried deleting your `token.json` in the MMM-trakt folder?

**Comment by ezar** [comment]
Yes. I deleted it. When I reboot, same problem.
At screen appears please enter to activate: undefined
Regards.

**Comment by ezar** [comment]
Nothing??

**Comment by Kiina** [comment]
Well I tested it locally and tried to reproduce a similar issue and the only way I could get the undefined is when there is an issue with the token.json. So if you set `client_id` and `client_secret` correctly and removed the token.json it should work

**Comment by ezar** [comment]
Nothing! I use correct `client_id` and `client_secret`. Module generate token, but doesnt works :(

**Comment by Kiina** [comment]
Can you pull the latest Version and check for the error log?

**Comment by ezar** [comment]
Now its working! Thanks :)
