### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by Menturan** [Kiina/MMM-trakt#9]
I added some styling to the data table, added a module header and removed the data table heading.
The size of the moudle could be configured by using the built in css classes - small, medium and large. Included the clock, in the screenshot, for reference.

I thought maybe we should discuss the styling before I drop a pull request.

![bild](https://user-images.githubusercontent.com/16061385/52978805-2007aa00-33d3-11e9-9ed7-a19ba685b9d3.png)

**Comment by Kiina** [comment]
Can you push these changes to your fork so I can take a look at it locally?

**Comment by Menturan** [comment]
Changes pushed. https://github.com/Menturan/MMM-trakt/commit/0e9f719f0241cc6ee3acec5d09f606d52696f17a .

I made it swiftly. Could really be improved. For example should the `object.style =...` be inserted into a separate css file. Thought I refactor it ones we agreed upon a certain style.

I took inspiration from the built-in calendar module. In my opinion should MM modules have a homogeneous appearance.

@Kiina What do you think?

**Comment by Menturan** [comment]
@Kiina Have you had time to look at it? :smiley:

**Comment by Kiina** [comment]
Yeah sorry, I've been running it on my Mirror for some time now. I really like how it looks, but I think the header should be left up to the user config or maybe have a default one that takes it into account and only shows when the user hasn't set `{ header: 'TV Shows' }`
